server:
  port: 8080
  servlet:
    encoding:
      force-response: true
spring:
  profiles:
    include:
      - secret
      - oauth
      - stmp
      - jwt

  # multipartFile 용량 늘려주는 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: redis

cloud:
  aws:
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug    # Logger
    org.hibernate.type: trace   # Show Query Parameter

