jwt:
  secretKey: '124215sdfhab8fr98234c2q4g87243cg'

  access:
    expiration: 1800000 # 30분 (1000L(ms -> s) * 60L(s -> m) * 30L)
    #    expiration: 60000 # 1분
    header: "Authorization"

  refresh:
    expiration: 1209600000 # 2주 (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: "Authorization-refresh"